### ISSUE TITLE
Disease datasets

### ISSUE THREAD

**Issue by ajayk1931** [gridclub/Hack2O#4]
Approximately when can we expect the water borne disease datasets to be released?

**Comment by emmakearney** [comment]
Hey! The only data set that was released is the Flint data set. See [here](http://gridclub.io/Hack2O/#dataset) for the data details. There are additional links for water-related data sets at the end of the slides - perhaps this is what you're referring to?

**Comment by ajayk1931** [comment]
Those work too. The description said additional disease datasets will be available, so I thought there would be more.

Thanks!
