### ISSUE TITLE
I found this document helpful to understand the samples....

### ISSUE THREAD

**Issue by Shujian2015** [gridclub/Hack2O#5]
I found this document is helpful for me to understand how the water was sampled:
https://www.epa.gov/sites/production/files/2016-06/documents/epa_flint_qapp-revision_2.pdf

Especially page 35 of 70: Appendix C - Lead Source/Release Diagnostic Evaluation.

**Comment by heyitsjoe** [comment]
Great call with the QUAPP. Probably should have provided that at the kickoff.

**Comment by heyitsjoe** [comment]
I should have provided that. Again, good find.

**Comment by Shujian2015** [comment]
:)
