### ISSUE TITLE
Recording of the presentation yesterday

### ISSUE THREAD

**Issue by AnirudhaDesai** [gridclub/Hack2O#6]
Hey! Where do we find the recording of the presentation that was given yesterday about the water slides?

**Comment by heyitsjoe** [comment]
https://drive.google.com/open?id=0B_azRDFhehcjTFB2ZlRPRXIzT0E

**Comment by salauer** [comment]
We only have the slides, not the recording (I believe). You can find them halfway down the page at [gridclub.io/Hack2O](http://gridclub.io/Hack2O) or directly [here](https://docs.google.com/presentation/d/1W7IeY7xIKBEuMQdJmzM5QxStgI7kr4AXS5lr1AkEmaA/edit#slide=id.p)

**Comment by AruniRC** [comment]
hey @Mario1212 -- the video is now up:
http://gridclub.io/Hack2O/#dataset

**Comment by kgourgou** [comment]
@salauer, close all issues.

**Comment by kgourgou** [comment]
:stuck_out_tongue_winking_eye:
